apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-access
  namespace: oppe2-app
  annotations:
    iam.gke.io/gcp-service-account: telemetry-access@ultra-guard-461512-j0.iam.gserviceaccount.com
